---
title: "Mathematical Proof"
author: "John Shea"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 12pt
output:
  pdf_document:
    extra_dependencies:
      - makecell
      - booktabs
      - float
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE)
```

# Assignment \#3

## Question 1

a. True
    - For all persons, it is not true that the given person is his or her own
      twin.
    - More succinctly: No one is their own twin.
b. False
    - There exists at least one person who is his or her own twin.
c. False
    - There exists at least one person who is twins with every other person.
d. False
    - For all people, there is not a single person with whom they are twins.
e. True
    - There exists at least one person who does not have a twin.
f. True
    - for all people, it is not true that they are twins with everyone.
    - More succinctly: No one is twins with everyone.

## Question 2

a. False: $\forall \textrm{x}(5 < \textrm{x} < 10 \rightarrow \exists
      \textrm{a} \exists \textrm{b} \exists
      \textrm{c}(\textrm{a}^2+\textrm{b}^2+\textrm{c}^2=\textrm{x})).$
    - becase we are dealing with $\mathbb{N}$, the numbers that $x$ needs to be to
      satisy $5<x<10\rightarrow \exists a \exists b \exists c(a^2+b^2+c^2=x)$ are 6,
      7, 8, and 9. The problem does not state that a, b, and c cannot be equal.
      Therefore, we can satisfy the following values:
        - x = 6: a = 1, b = 1, c = 2.
        - x = 8: a = 0, b = 2, c = 2.
        - x = 9: a = 0, b = 0, c = 3; or a = 1, b = 2, c = 2.
    - However, no combination of natural numbers can provide x a value of 7.
    - **It should be noted that the designations of the variable (i.e. a, b, c) are
      inconsequential to the result. There values can be interchanged in any of the
      examples and the meaning is still the same. It only matters that the three
      variable in total take on the three values specified.**
b. True: $\exists!\textrm{x}((x-4)^2=36).$
    - This statement asserts that one, and only one, natural number can render
      $(x-4)^2 = 36$ true.
    - The number 10 accomplishes this: $10 - 4 = 6, 6^2=36$.
    - Any natural number greater than 10 produces a number inside the parenthesis
      greater than 6 and, thus, results in an answer greater than 36.
    - Any natural number less than 10 produces a number positive number less
      than 6 or a negative number greater than -6 inside the parenthesis and
      thus resluts in an answer less than 36.
    - If dealing with the set $\mathbb{Z}$ instead of $\mathbb{N}$, then $-2$ would
      be an answer as it would produce -6 inside the parenthesis, which results in
      $36$ as the answer. However, the set $\mathbb{N}$ prohibits the use of
      negative numbers.
c. False: $\exists!\textrm{x}((x-11)^2=49).$
    - This statement asserts that one, and only one, natural number can render
      $(x-11)^2=49$ true.
    - This statement is false because there are two natural numbers that can
      accomplish this.
        - $x = 18$: $18-11=7, 7^2=49$.
        - $x=4$: $4-11=-7, (-7)^2=49$.
d. False: $\exists x \exists y(((x \ne y) \land (x-4)^2=36) \land (y-4)^2=36).$
    - This is false for the same reason that b was true. Only one natural number --
      6 -- produces 36 when plugged into this equation. If dealing with the set
      $\mathbb{Z}$ then this would be true (10 and -2) and statemeent b would be
      false. However in the set $\mathbb{N}$, only 10 produces the desired result.

## Question #3

\input{question_three.tex}

## Question 4

a. The identity element for multiplication is 1.
    - $\forall x \in \mathbb{R}(x \cdot 1 = x).$

b. Every positive real number has a positive multiplicative inverse.
    - $\forall x \in \mathbb{R}^+ \exists y((x \cdot y = 1) \land (x > 0))$; or
    - $\forall x \in \mathbb{R}^+ \exists y \in \mathbb{R}^+(x \cdot y = 1).$

c. No positive real number has a negative multiplicative inverse.
    - $\forall x \in \mathbb{R}^+ \exists y(x \cdot y = 1 \rightarrow y > 0)$;
      or
    - $\neg\exists x \in \mathbb{R}^+ \exists y((x \cdot y = 1) \land (y < 0)).$


## Question 5

a.
    - $A_2 = \{2, 3, 4, 6\}$
        - j = 2
        - j + 1 = 3
        - j + 2 = 4
        - 2j = 4 (only one 4 is included in the set
          because two is superflous)
        - 3j = 6
    - $A_3 = \{3, 4, 5, 6, 9\}$
        - j = 3
        - j + 1 = 4
        - j + 2 = 5
        - 2j = 6
        - 3j = 9
    - $A_4 = \{4, 5, 6, 8, 12\}$
        - j = 4
        - j + 1 = 5
        - j + 2 = 6
        - 2j = 8
        - 3j = 12
b.
    - $\cap_{j \in J} A_j = \{4, 6\}$
    - $\cup_{j \in J} A_j = \{2, 3, 4, 5, 6, 8, 9, 12\}$


## Question 6

a. $\wp (A) \cup \wp (B) \subseteq \wp (A \cup B)$
    - $\wp (A) \cup \wp (B)$ means that $\forall X \in (\wp (A) \cup \wp (B))(X
      \subseteq A \lor \subseteq B)$. According to the principles of Set Theory,
      this is equivalent to $X \subseteq \wp (A \cup B)$.
b. Fasle: $\wp (A) \cup \wp (B)=\wp (A) \cup B$
    - Suppose $A=\{1,2\}$, $B=\{2,3\}$, and $A \cup B = \{1, 2, 3\}$.
      Then $\wp (A)=\{\emptyset, \{1\},\{2\}, \{1,2\}\}$
      and $\wp (B)=\{\emptyset, \{2\}, \{3\}, \{2,3\}\}$.
      Therefore $\wp (A) \cup \wp (B)=\{\emptyset, \{1\}, \{2\}, \{3\}, \{1, 2\}, \{2, 3\}\}$.
      Whereas $\wp (A \cup B)=\{\emptyset, \{1\}, \{2\}, \{3\}, \{1, 2\}, \{2, 3\},\\ \{1, 3\},
      \{1, 2, 3\}\}$.
      Clearly, $\wp (A \cup B)$ has subsets ${1, 3}$ and ${1, 2, 3}$ that are not
      present in $\wp (A) \cup \wp (B)$. Therefore $\wp (A) \cup \wp (B) \ne\wp (A \cup B).$ 

